spring.application.name=VictimService
server.address=0.0.0.0
server.port=5005
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://nimargsns_db_user:Gh3mwydHtp19EZ6h@cluster0.drvnfnl.mongodb.net/VictimDB?retryWrites=true&w=majority}

jwt.secret=IAmSonOfGurvinderSinghWithNameHarnimarPreetSinghAge19AndSexMaleWantingAFemale
jwt.expirationMs=86400000
auth.service.url=${AUTH_SERVICE_URL:https://capstone-sprint-1.vercel.app}
ai.service.url=${AI_SERVICE_URL:https://flood-severity-analyzer.vercel.app/api/v1/score-base64}
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:tcardfrt}
cloudinary.api-key=${CLOUDINARY_API_KEY:365943294178567}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:6b2ZoYFtGH7bszcgG7Szk84KzUc}
